application:
  api_keys:
    steamapis: 6WJY9LtExOCmvzVeqw8GaAxjwWM
  contract:
    parse_collections: false # Необходимо ли парсить коллекции и предметы
    parse_prices: false # Необходимо ли парсить ли цены предметов
    include_stat_trak: false # Включить ли StatTrak предметы в поиск
    type: one # Тип контрактов. one - в рамках одной коллекции, all - в рамках всех коллекций
    result: file # Куда записывать результат. file - файл в корне проекта, db - в базу данных
    trade_market: STEAM # The trading market at the prices of which the calculation is made. STEAM, LOOT_FARM
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/econtracts
    username: econtracts_user
    password: stcartnoce
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: update